"""`docs/reference/cheatsheet.md`: every call in the pythonic layer, listed.

Generated by introspection rather than written, for the same reason as the
enumeration reference: a hand-kept list of two hundred members goes stale
without anyone noticing, and a reference that lies is worse than none. Every
signature here is read from the installed package, and every description is
the first line of that member's own docstring.

Needs no SOLIDWORKS: importing `swcomapi.api` imports no COM object.
"""

import importlib
import inspect
import os
import pkgutil

# The order the sections come out in: how the work actually goes, from getting
# hold of the application to writing a file out, rather than alphabetically.
ORDER = [
    "app",
    "document",
    "sketch",
    "modeling",
    "patterns",
    "reference",
    "selection",
    "features",
    "dimensions",
    "configurations",
    "equations",
    "properties",
    "materials",
    "geometry",
    "sheetmetal",
    "components",
    "mates",
    "drawing",
    "export",
]

# What each section is for, in one line. Keyed by module name.
BLURBS = {
    "app": "Getting hold of SOLIDWORKS, and the documents it has open.",
    "document": "Anything open: a part, an assembly or a drawing.",
    "sketch": "Drawing, and reading a sketch back.",
    "modeling": "Turning a sketch into geometry.",
    "features": "The tree, and suppression.",
    "dimensions": "Named dimensions, in millimetres and degrees.",
    "configurations": "The configurations of a document.",
    "equations": "Equations and global variables.",
    "properties": "Custom properties, as a mapping.",
    "materials": "Reading and applying a material.",
    "geometry": "Bodies, faces, edges and vertices.",
    "sheetmetal": "Thickness, bend radius and K-factor.",
    "components": "The components of an assembly.",
    "drawing": "Sheets and views.",
    "export": "Writing a file out, and decoding what went wrong.",
}

# Conventions that hold everywhere, so they are stated once at the top rather
# than repeated against two hundred entries.
PREAMBLE = """Every call in the pythonic layer, with the signature read from
the installed package and the description taken from its own docstring. Run
`python -m swcomapi.tools cheatsheet` to rebuild it; do not edit it by hand.

For what a call does in detail, and for the traps, see
[`DOCUMENTATION.md`](../../DOCUMENTATION.md). For the 19,874 members of the
COM API underneath, use `swcomapi.find` and `swcomapi.describe`.

## What holds everywhere

- **Millimetres and degrees**, everywhere. SOLIDWORKS works in metres and
  radians and this package converts. The one exception is equations, which
  are in the document's own units, because an equation is a string
  SOLIDWORKS parses rather than a number it stores.
- **Points are tuples**: `(x, y)` in a sketch, `(x, y, z)` in space.
- **The raw COM object is always there**, on `.com`, on every wrapper.
- **Names SOLIDWORKS reserves cannot be used for a global variable.**
  `thickness` is one: it drives sheet metal, and the equation manager
  refuses it.
- A dimension's name is `Dimension@Feature`, or `Dimension@Feature@Document`.
"""


def _summary(obj):
    """The first line of an object's docstring, as Markdown.

    The docstrings are reStructuredText, where a literal is written ``like
    this``; Markdown wants one backtick. A pipe would end a table cell, so it
    is escaped. Empty when there is no docstring.
    """
    text = inspect.getdoc(obj) or ""
    first = text.split("\n", 1)[0].strip()
    return first.replace("``", "`").replace("|", "\\|")


def _signature(name, obj, drop_self=False):
    """``name(a, b=1)``, as a str, with ``self`` left out of a method."""
    try:
        signature = inspect.signature(obj)
    except (TypeError, ValueError):
        return name
    parameters = list(signature.parameters.values())
    if drop_self and parameters and parameters[0].name == "self":
        parameters = parameters[1:]
    rendered = signature.replace(parameters=parameters)
    return f"{name}{rendered}"


def _members_of(cls):
    """One ``(rendered, summary)`` pair per public member, in source order."""
    found = []
    for name, value in vars(cls).items():
        if name.startswith("_"):
            continue
        if isinstance(value, property):
            access = "get/set" if value.fset else "get"
            found.append((f".{name}", f"[{access}] {_summary(value.fget)}"))
        elif inspect.isfunction(value):
            found.append((f".{_signature(name, value, drop_self=True)}", _summary(value)))
    return found


def _module_section(module):
    """The Markdown for one module, as a list of str."""
    lines = []
    for name, value in vars(module).items():
        if name.startswith("_") or getattr(value, "__module__", None) != module.__name__:
            continue

        if inspect.isclass(value):
            members = _members_of(value)
            if not members:
                continue
            lines.append(f"### `{name}`")
            lines.append("")
            lines.append(_summary(value))
            lines.append("")
            lines.append("| call | what it does |")
            lines.append("|---|---|")
            for rendered, summary in members:
                lines.append(f"| `{rendered}` | {summary} |")
            lines.append("")

        elif inspect.isfunction(value):
            lines.append(f"### `{_signature(name, value)}`")
            lines.append("")
            lines.append(_summary(value))
            lines.append("")

    return lines


def cheatsheet():
    """The whole reference, as a str of Markdown."""
    from .. import api

    present = {module.name for module in pkgutil.iter_modules(api.__path__)}
    ordered = [name for name in ORDER if name in present]
    ordered += sorted(present - set(ORDER))

    lines = ["# Cheat sheet", "", PREAMBLE.strip(), ""]

    lines.append("## Connecting")
    lines.append("")
    lines.append("| call | what it does |")
    lines.append("|---|---|")
    from .. import session

    for name in ("connect", "attach", "launch"):
        function = getattr(session, name)
        lines.append(f"| `swc.{_signature(name, function)}` | {_summary(function)} |")
    lines.append("")

    counted = 0
    for name in ordered:
        module = importlib.import_module(f"swcomapi.api.{name}")
        section = _module_section(module)
        if not section:
            continue
        counted += sum(1 for line in section if line.startswith("| `"))
        lines.append(f"## `{name}`")
        lines.append("")
        if name in BLURBS:
            lines.append(BLURBS[name])
            lines.append("")
        lines.extend(section)

    lines.append("---")
    lines.append("")
    lines.append(f"{counted} members across {len(ordered)} modules.")
    lines.append("")
    return "\n".join(lines)


def write_cheatsheet(root=None):
    """Write `docs/reference/cheatsheet.md`. Returns ``(path, size)``."""
    from .generate import package_root

    # package_root() is <repo>/src/swcomapi, so the repository is two up.
    repository = os.path.dirname(os.path.dirname(package_root()))
    target = os.path.join(root or repository, "docs", "reference", "cheatsheet.md")
    os.makedirs(os.path.dirname(target), exist_ok=True)
    text = cheatsheet()
    with open(target, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    return target, len(text.encode("utf-8"))
