"""Turn the installed type libraries into the generated layer.

    python -m swcomapi.tools generate

Reads every type library the install has, checks the assumptions the emitted
code relies on, and writes:

``swcomapi/generated/_meta.py``
    what was read: library names, GUIDs, versions, counts. No timestamp - see
    below.
``swcomapi/generated/_enum_data.py``
    every enumeration as plain dicts. Data only, so importing it costs
    almost nothing.
``swcomapi/enums.pyi`` and ``swcomapi/const.pyi``
    stubs declaring all 1,434 enumerations and all 14,889 constants, so the
    editor and mypy see the whole thing even though it is built at runtime.

Why data plus a stub, rather than 1,434 real ``IntEnum`` classes in a module?
Because it was measured. The same 14,889 members, three ways, on Python 3.14,
with the interpreter's own 40 ms start-up subtracted:

===============================  ========  ==============
shape                            size      import cost
===============================  ========  ==============
1,434 real IntEnum classes       655 KB    ~158 ms
plain dicts                      740 KB    ~0 ms
dicts + IntEnum built on demand  740 KB    ~8 ms
===============================  ========  ==============

158 ms on every ``import`` is a lot to pay for a library, and you pay it even
if you touch one constant. The third shape costs a twentieth of that, still
hands you a real ``IntEnum`` when you ask for one, and the stub means the
editor cannot tell the difference.

Determinism
-----------

The output carries no timestamp and no generating-machine path, and everything
is sorted. Regenerating against the same SOLIDWORKS must leave ``git status``
clean; that is a test. A timestamp would make every regeneration a diff and
the check worthless.
"""

import os
import textwrap

from ..api.app import year_from_major
from . import install, tlb

# Where the output goes, relative to the package root (src/swcomapi).
GENERATED_DIR = "generated"

HEADER = '''"""{summary}

Generated by ``python -m swcomapi.tools generate``. Do not edit.

Source: {source}
"""
'''


class GenerationError(RuntimeError):
    """The libraries broke an assumption the generated code relies on."""


# ------------------------------------------------------------------ gathering


def gather(paths=None):
    """Read every library and fold it into one picture of the API.

    Returns a dict::

        {
          "libraries": [ {"name", "file", "guid", "major", "minor", "doc"} ],
          "enums": {name: {"members": [(name, value)], "library": "SwConst",
                           "guid": ..., "doc": ...}},
          "interfaces": {name: {...as tlb.read_interface, plus "library"}},
          "failed": [(file, error)],
          "year": 2026,
        }

    Libraries that will not load are recorded in ``failed`` rather than
    swallowed: ``cosworks.tlb`` needs a DLL that is only on the path when
    Simulation is installed, and that is worth saying out loud.
    """
    paths = paths if paths is not None else install.library_paths()
    if not paths:
        raise GenerationError(
            "no type libraries found. Is SOLIDWORKS installed? "
            f"Set {install.DIR_ENV} to point at it."
        )

    libraries = []
    enums = {}
    interfaces = {}
    failed = []

    for path in sorted(paths, key=lambda p: os.path.basename(p).lower()):
        filename = os.path.basename(path)
        try:
            lib = tlb.read_library(path)
        except Exception as exc:
            failed.append((filename, str(exc)))
            continue

        libraries.append(
            {
                "name": lib["name"],
                "file": filename,
                "guid": lib["guid"],
                "major": lib["major"],
                "minor": lib["minor"],
                "doc": lib["doc"],
            }
        )

        for enum in lib["enums"]:
            _add_enum(enums, enum, lib["name"])
        for interface in lib["interfaces"]:
            _add_interface(interfaces, interface, lib["name"])

    return {
        "libraries": libraries,
        "enums": dict(sorted(enums.items())),
        "interfaces": dict(sorted(interfaces.items())),
        "failed": failed,
        "year": _release_year(libraries),
    }


def _release_year(libraries):
    """The SOLIDWORKS release year, from sldworks.tlb's version.

    Only that library counts. The add-in libraries version themselves
    independently - Simulation's cosworks.tlb is at major 19 while SOLIDWORKS
    2026 is at 34 - so taking whichever library happened to be read first would
    give the wrong answer, or none at all.
    """
    for lib in libraries:
        if lib["file"].lower() == "sldworks.tlb":
            return year_from_major(lib["major"])
    return None


def _add_enum(enums, enum, library):
    """Fold one enumeration in, refusing to silently overwrite a different one."""
    name = enum["name"]
    existing = enums.get(name)
    if existing is not None:
        if dict(existing["members"]) != dict(enum["members"]):
            raise GenerationError(
                f"{name} is defined differently in {existing['library']} and "
                f"{library}; the generator cannot choose between them"
            )
        return
    enums[name] = {
        "members": enum["members"],
        "library": library,
        "guid": enum["guid"],
        "doc": enum["doc"],
    }


def _add_interface(interfaces, interface, library):
    """Fold one interface in. The first library to define a name wins.

    Several libraries republish the same interface - ``swpublished.tlb``
    repeats parts of ``sldworks.tlb`` - and the definitions agree, so there is
    nothing to choose between.
    """
    name = interface["name"]
    if name in interfaces:
        return
    interfaces[name] = dict(interface, library=library)


# ------------------------------------------------------------------- checking


def check(api):
    """Verify what the emitted code assumes. Raises `GenerationError`.

    Measured true on SOLIDWORKS 2026, but asserted rather than trusted: these
    are the properties that make a flat constant namespace safe, and a future
    release could break any of them.
    """
    problems = []

    for name, enum in api["enums"].items():
        if not name.isidentifier():
            problems.append(f"enum name {name!r} is not a valid Python identifier")
        seen = set()
        for member, _ in enum["members"]:
            if not member.isidentifier():
                problems.append(f"{name}.{member} is not a valid Python identifier")
            if member in seen:
                problems.append(f"{name} declares {member!r} twice")
            seen.add(member)

    # The flat namespace in swcomapi.const only works because every constant
    # name is unique across all 1,434 enumerations. Dassault prefixes
    # everything, so it holds - but if it ever stops holding, emitting a
    # namespace that quietly picks one value would be far worse than failing.
    owners = {}
    for name, enum in api["enums"].items():
        for member, value in enum["members"]:
            previous = owners.get(member)
            if previous is not None and previous[1] != value:
                problems.append(
                    f"constant {member!r} means {previous[1]} in {previous[0]} "
                    f"but {value} in {name}"
                )
            owners[member] = (name, value)

    if problems:
        raise GenerationError(
            f"{len(problems)} problem(s) in the type libraries:\n  "
            + "\n  ".join(problems[:20])
        )


def counts(api):
    """The headline numbers, as a dict. Emitted into `_meta` and printed."""
    members = [m for i in api["interfaces"].values() for m in i["members"]]
    return {
        "libraries": len(api["libraries"]),
        "enums": len(api["enums"]),
        "constants": sum(len(e["members"]) for e in api["enums"].values()),
        "interfaces": len(api["interfaces"]),
        "members": len(members),
        "documented": sum(1 for m in members if m["doc"]),
        "properties": sum(1 for m in members if m["kind"] in ("get", "put")),
        "with_out": sum(1 for m in members if m["has_out"]),
        "com_only": sum(1 for m in members if m["com_only"]),
    }


# ------------------------------------------------------------------- emitting


def emit_meta(api):
    """`generated/_meta.py`: what this generated layer was built from."""
    source = _source_line(api)
    out = [HEADER.format(summary="What the generated layer was built from.", source=source)]

    out.append(f"SOLIDWORKS_YEAR = {api['year']!r}\n")
    out.append("\n# The type libraries that were read, in the order they were read.")
    out.append("LIBRARIES = [")
    for lib in api["libraries"]:
        out.append("    {")
        for key in ("name", "file", "guid", "major", "minor", "doc"):
            out.append(f"        {key!r}: {lib[key]!r},")
        out.append("    },")
    out.append("]\n")

    if api["failed"]:
        out.append("\n# Libraries present but not loadable on the generating machine.")
        out.append("# Usually a missing add-in DLL rather than a broken file.")
        out.append("UNREADABLE = [")
        for filename, error in api["failed"]:
            out.append(f"    ({filename!r}, {error!r}),")
        out.append("]\n")
    else:
        # Annotated because an empty list tells mypy nothing, and this module
        # is type checked like any other.
        out.append("\nUNREADABLE: list[tuple[str, str]] = []\n")

    out.append("\n# Headline sizes, so `swcomapi.generated` can report itself.")
    out.append("COUNTS = {")
    for key, value in counts(api).items():
        out.append(f"    {key!r}: {value},")
    out.append("}")
    return "\n".join(out) + "\n"


def emit_enum_data(api):
    """`generated/_enum_data.py`: every enumeration as plain data.

    Members keep the order the library declares them in, which is the order the
    documentation lists. Values are written as-is, so a negative or a wide flag
    value survives untouched.
    """
    source = _source_line(api)
    out = [
        HEADER.format(
            summary="Every SOLIDWORKS enumeration, as plain data.", source=source
        )
    ]
    out.append(
        "# Data only: no classes are built here, so importing this module is\n"
        "# almost free. `swcomapi.enums` turns an entry into a real IntEnum the\n"
        "# first time you ask for it, and `swcomapi.const` flattens them all\n"
        "# into one namespace the way VBA sees them.\n"
    )

    out.append("ENUMS = {")
    for name, enum in api["enums"].items():
        out.append(f"    {name!r}: {{")
        for member, value in enum["members"]:
            out.append(f"        {member!r}: {value!r},")
        out.append("    },")
    out.append("}\n")

    out.append("\n# Which type library each enumeration came from.")
    out.append("ENUM_LIBRARY = {")
    for name, enum in api["enums"].items():
        out.append(f"    {name!r}: {enum['library']!r},")
    out.append("}")
    return "\n".join(out) + "\n"


def emit_enums_stub(api):
    """`enums.pyi`: one IntEnum class per enumeration, for the editor.

    The classes really are built at runtime, by `swcomapi.enums.__getattr__`;
    this is what lets an editor and mypy see them without paying for them.
    """
    out = [
        '"""Stub for swcomapi.enums. Generated, do not edit.',
        "",
        f"Source: {_source_line(api)}",
        '"""',
        "",
        "from enum import IntEnum",
        "",
    ]
    for name, enum in api["enums"].items():
        out.append(f"class {name}(IntEnum):")
        doc = enum["doc"] or _enum_summary(name, enum)
        out.append(f'    """{doc}"""')
        if not enum["members"]:
            out.append("    ...")
        for member, value in enum["members"]:
            # Deliberately unannotated: the typing spec requires enum
            # members in a stub to be bare assignments.
            out.append(f"    {member} = {value}")
        out.append("")
    return "\n".join(out) + "\n"


def emit_const_stub(api):
    """`const.pyi`: every constant as a module-level int, for the editor."""
    out = [
        '"""Stub for swcomapi.const. Generated, do not edit.',
        "",
        "Every enumeration member as a plain module-level name, the way VBA",
        "sees them.",
        "",
        f"Source: {_source_line(api)}",
        '"""',
        "",
    ]
    for name, enum in api["enums"].items():
        out.append(f"# {name} ({enum['library']})")
        for member, value in enum["members"]:
            out.append(f"{member}: int = {value}")
        out.append("")
    return "\n".join(out) + "\n"


def emit_generated_init(api):
    """`generated/__init__.py`."""
    numbers = counts(api)
    summary = textwrap.dedent(
        f"""\
        Machine-generated data. Do not edit anything in this package.

        Everything here was read out of the type libraries that ship with the
        installed SOLIDWORKS, by ``python -m swcomapi.tools generate``. It is
        committed to the repository on purpose: the package must install and
        its constants must work on a machine with no SOLIDWORKS on it.

        What was read:

        * {numbers['libraries']} type libraries
        * {numbers['enums']} enumerations, {numbers['constants']} constants
        * {numbers['interfaces']} interfaces, {numbers['members']} members
        * {numbers['documented']} of those members carry a description
        * {numbers['with_out']} have an ``[out]`` parameter
        """
    ).rstrip()
    out = [HEADER.format(summary=summary, source=_source_line(api))]
    out.append("from ._meta import COUNTS, LIBRARIES, SOLIDWORKS_YEAR, UNREADABLE")
    out.append("")
    out.append('__all__ = ["COUNTS", "LIBRARIES", "SOLIDWORKS_YEAR", "UNREADABLE"]')
    return "\n".join(out) + "\n"


def _enum_summary(name, enum):
    """A one-line description for an enumeration that has none.

    Not one of the 14,889 constants carries a description in the type
    libraries, and nor do most enumerations, so the stub says something
    factual rather than nothing.
    """
    return f"{name} ({len(enum['members'])} constants, from {enum['library']})."


def _source_line(api):
    """The provenance line for a generated file's docstring.

    Names the release and the libraries, never a path or a timestamp: the
    output has to be byte-identical when regenerated from the same install.
    """
    year = api["year"] or "unknown"
    files = ", ".join(lib["file"] for lib in api["libraries"])
    line = f"SOLIDWORKS {year} type libraries ({files})"
    # Ten library names overflow any sensible line length, so it is wrapped
    # here rather than left for the linter to complain about.
    return "\n".join(textwrap.wrap(line, width=78, subsequent_indent="  "))


# -------------------------------------------------------------------- writing


def package_root():
    """The ``src/swcomapi`` directory this module lives in."""
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def write(api, root=None):
    """Write every generated file. Returns a list of (path, bytes_written).

    Files are written with explicit UTF-8 and Unix newlines, so that the
    output does not depend on the machine's locale or on git's autocrlf.
    """
    root = root or package_root()
    generated = os.path.join(root, GENERATED_DIR)
    os.makedirs(generated, exist_ok=True)

    files = {
        os.path.join(generated, "__init__.py"): emit_generated_init(api),
        os.path.join(generated, "_meta.py"): emit_meta(api),
        os.path.join(generated, "_enum_data.py"): emit_enum_data(api),
        os.path.join(root, "enums.pyi"): emit_enums_stub(api),
        os.path.join(root, "const.pyi"): emit_const_stub(api),
    }

    written = []
    for path, text in sorted(files.items()):
        with open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
        written.append((path, len(text.encode("utf-8"))))
    return written


def run(paths=None, root=None):
    """Gather, check and write. Returns ``(api, written)``."""
    api = gather(paths)
    check(api)
    return api, write(api, root)
