"""Turn the installed type libraries into the generated layer.

    python -m swcomapi.tools generate

Reads every type library the install has, checks the assumptions the emitted
code relies on, and writes:

``swcomapi/generated/_meta.py``
    what was read: library names, GUIDs, versions, counts. No timestamp - see
    below.
``swcomapi/generated/_enum_data.py``
    every enumeration as plain dicts. Data only, so importing it costs
    almost nothing.
``swcomapi/enums.pyi`` and ``swcomapi/const.pyi``
    stubs declaring all 1,434 enumerations and all 14,889 constants, so the
    editor and mypy see the whole thing even though it is built at runtime.

Why data plus a stub, rather than 1,434 real ``IntEnum`` classes in a module?
Because it was measured. The same 14,889 members, three ways, on Python 3.14,
with the interpreter's own 40 ms start-up subtracted:

===============================  ========  ==============
shape                            size      import cost
===============================  ========  ==============
1,434 real IntEnum classes       655 KB    ~158 ms
plain dicts                      740 KB    ~0 ms
dicts + IntEnum built on demand  740 KB    ~8 ms
===============================  ========  ==============

158 ms on every ``import`` is a lot to pay for a library, and you pay it even
if you touch one constant. The third shape costs a twentieth of that, still
hands you a real ``IntEnum`` when you ask for one, and the stub means the
editor cannot tell the difference.

Determinism
-----------

The output carries no timestamp and no generating-machine path, and everything
is sorted. Regenerating against the same SOLIDWORKS must leave ``git status``
clean; that is a test. A timestamp would make every regeneration a diff and
the check worthless.
"""

import os
import textwrap

from ..api.app import year_from_major
from . import install, tlb

# Where the output goes, relative to the package root (src/swcomapi).
GENERATED_DIR = "generated"

HEADER = '''"""{summary}

Generated by ``python -m swcomapi.tools generate``. Do not edit.

Source: {source}
"""
'''


class GenerationError(RuntimeError):
    """The libraries broke an assumption the generated code relies on."""


# ------------------------------------------------------------------ gathering


def gather(paths=None):
    """Read every library and fold it into one picture of the API.

    Returns a dict::

        {
          "libraries": [ {"name", "file", "guid", "major", "minor", "doc"} ],
          "enums": {name: {"members": [(name, value)], "library": "SwConst",
                           "guid": ..., "doc": ...}},
          "interfaces": {name: {...as tlb.read_interface, plus "library"}},
          "failed": [(file, error)],
          "year": 2026,
        }

    Libraries that will not load are recorded in ``failed`` rather than
    swallowed: ``cosworks.tlb`` needs a DLL that is only on the path when
    Simulation is installed, and that is worth saying out loud.
    """
    paths = paths if paths is not None else install.library_paths()
    if not paths:
        raise GenerationError(
            "no type libraries found. Is SOLIDWORKS installed? "
            f"Set {install.DIR_ENV} to point at it."
        )

    libraries = []
    enums = {}
    interfaces = {}
    failed = []

    for path in sorted(paths, key=lambda p: os.path.basename(p).lower()):
        filename = os.path.basename(path)
        try:
            lib = tlb.read_library(path)
        except Exception as exc:
            failed.append((filename, str(exc)))
            continue

        libraries.append(
            {
                "name": lib["name"],
                "file": filename,
                "guid": lib["guid"],
                "major": lib["major"],
                "minor": lib["minor"],
                "doc": lib["doc"],
            }
        )

        for enum in lib["enums"]:
            _add_enum(enums, enum, lib["name"])
        for interface in lib["interfaces"]:
            _add_interface(interfaces, interface, lib["name"])

    return {
        "libraries": libraries,
        "enums": dict(sorted(enums.items())),
        "interfaces": dict(sorted(interfaces.items())),
        "failed": failed,
        "year": _release_year(libraries),
    }


def _release_year(libraries):
    """The SOLIDWORKS release year, from sldworks.tlb's version.

    Only that library counts. The add-in libraries version themselves
    independently - Simulation's cosworks.tlb is at major 19 while SOLIDWORKS
    2026 is at 34 - so taking whichever library happened to be read first would
    give the wrong answer, or none at all.
    """
    for lib in libraries:
        if lib["file"].lower() == "sldworks.tlb":
            return year_from_major(lib["major"])
    return None


def _add_enum(enums, enum, library):
    """Fold one enumeration in, refusing to silently overwrite a different one."""
    name = enum["name"]
    existing = enums.get(name)
    if existing is not None:
        if dict(existing["members"]) != dict(enum["members"]):
            raise GenerationError(
                f"{name} is defined differently in {existing['library']} and "
                f"{library}; the generator cannot choose between them"
            )
        return
    enums[name] = {
        "members": enum["members"],
        "library": library,
        "guid": enum["guid"],
        "doc": enum["doc"],
    }


def _add_interface(interfaces, interface, library):
    """Fold one interface in. The first library to define a name wins.

    Several libraries republish the same interface - ``swpublished.tlb``
    repeats parts of ``sldworks.tlb`` - and the definitions agree, so there is
    nothing to choose between.
    """
    name = interface["name"]
    if name in interfaces:
        return
    interfaces[name] = dict(interface, library=library)


# ------------------------------------------------------------------- checking


def check(api):
    """Verify what the emitted code assumes. Raises `GenerationError`.

    Measured true on SOLIDWORKS 2026, but asserted rather than trusted: these
    are the properties that make a flat constant namespace safe, and a future
    release could break any of them.
    """
    problems = []

    for name, enum in api["enums"].items():
        if not name.isidentifier():
            problems.append(f"enum name {name!r} is not a valid Python identifier")
        seen = set()
        for member, _ in enum["members"]:
            if not member.isidentifier():
                problems.append(f"{name}.{member} is not a valid Python identifier")
            if member in seen:
                problems.append(f"{name} declares {member!r} twice")
            seen.add(member)

    # The flat namespace in swcomapi.const only works because every constant
    # name is unique across all 1,434 enumerations. Dassault prefixes
    # everything, so it holds - but if it ever stops holding, emitting a
    # namespace that quietly picks one value would be far worse than failing.
    owners = {}
    for name, enum in api["enums"].items():
        for member, value in enum["members"]:
            previous = owners.get(member)
            if previous is not None and previous[1] != value:
                problems.append(
                    f"constant {member!r} means {previous[1]} in {previous[0]} "
                    f"but {value} in {name}"
                )
            owners[member] = (name, value)

    if problems:
        raise GenerationError(
            f"{len(problems)} problem(s) in the type libraries:\n  "
            + "\n  ".join(problems[:20])
        )


def counts(api):
    """The headline numbers, as a dict. Emitted into `_meta` and printed."""
    members = [m for i in api["interfaces"].values() for m in i["members"]]
    return {
        "libraries": len(api["libraries"]),
        "enums": len(api["enums"]),
        "constants": sum(len(e["members"]) for e in api["enums"].values()),
        "interfaces": len(api["interfaces"]),
        "members": len(members),
        "documented": sum(1 for m in members if m["doc"]),
        "properties": sum(1 for m in members if m["kind"] in ("get", "put")),
        "with_out": sum(1 for m in members if m["has_out"]),
        "com_only": sum(1 for m in members if m["com_only"]),
    }


# ------------------------------------------------------------------- emitting


def emit_meta(api):
    """`generated/_meta.py`: what this generated layer was built from."""
    source = _source_line(api)
    out = [HEADER.format(summary="What the generated layer was built from.", source=source)]

    out.append(f"SOLIDWORKS_YEAR = {api['year']!r}\n")
    out.append("\n# The type libraries that were read, in the order they were read.")
    out.append("LIBRARIES = [")
    for lib in api["libraries"]:
        out.append("    {")
        for key in ("name", "file", "guid", "major", "minor", "doc"):
            out.append(f"        {key!r}: {lib[key]!r},")
        out.append("    },")
    out.append("]\n")

    if api["failed"]:
        out.append("\n# Libraries present but not loadable on the generating machine.")
        out.append("# Usually a missing add-in DLL rather than a broken file.")
        out.append("UNREADABLE = [")
        for filename, error in api["failed"]:
            out.append(f"    ({filename!r}, {error!r}),")
        out.append("]\n")
    else:
        # Annotated because an empty list tells mypy nothing, and this module
        # is type checked like any other.
        out.append("\nUNREADABLE: list[tuple[str, str]] = []\n")

    out.append("\n# Headline sizes, so `swcomapi.generated` can report itself.")
    out.append("COUNTS = {")
    for key, value in counts(api).items():
        out.append(f"    {key!r}: {value},")
    out.append("}")
    return "\n".join(out) + "\n"


def emit_enum_data(api):
    """`generated/_enum_data.py`: every enumeration as plain data.

    Members keep the order the library declares them in, which is the order the
    documentation lists. Values are written as-is, so a negative or a wide flag
    value survives untouched.
    """
    source = _source_line(api)
    out = [
        HEADER.format(
            summary="Every SOLIDWORKS enumeration, as plain data.", source=source
        )
    ]
    out.append(
        "# Data only: no classes are built here, so importing this module is\n"
        "# almost free. `swcomapi.enums` turns an entry into a real IntEnum the\n"
        "# first time you ask for it, and `swcomapi.const` flattens them all\n"
        "# into one namespace the way VBA sees them.\n"
    )

    out.append("ENUMS = {")
    for name, enum in api["enums"].items():
        out.append(f"    {name!r}: {{")
        for member, value in enum["members"]:
            out.append(f"        {member!r}: {value!r},")
        out.append("    },")
    out.append("}\n")

    out.append("\n# Which type library each enumeration came from.")
    out.append("ENUM_LIBRARY = {")
    for name, enum in api["enums"].items():
        out.append(f"    {name!r}: {enum['library']!r},")
    out.append("}")
    return "\n".join(out) + "\n"


def emit_enums_stub(api):
    """`enums.pyi`: one IntEnum class per enumeration, for the editor.

    The classes really are built at runtime, by `swcomapi.enums.__getattr__`;
    this is what lets an editor and mypy see them without paying for them.
    """
    out = [
        '"""Stub for swcomapi.enums. Generated, do not edit.',
        "",
        f"Source: {_source_line(api)}",
        '"""',
        "",
        "from enum import IntEnum",
        "",
    ]
    for name, enum in api["enums"].items():
        out.append(f"class {name}(IntEnum):")
        doc = enum["doc"] or _enum_summary(name, enum)
        out.append(f'    """{doc}"""')
        if not enum["members"]:
            out.append("    ...")
        for member, value in enum["members"]:
            # Deliberately unannotated: the typing spec requires enum
            # members in a stub to be bare assignments.
            out.append(f"    {member} = {value}")
        out.append("")
    return "\n".join(out) + "\n"


def emit_const_stub(api):
    """`const.pyi`: every constant as a module-level int, for the editor."""
    out = [
        '"""Stub for swcomapi.const. Generated, do not edit.',
        "",
        "Every enumeration member as a plain module-level name, the way VBA",
        "sees them.",
        "",
        f"Source: {_source_line(api)}",
        '"""',
        "",
    ]
    for name, enum in api["enums"].items():
        out.append(f"# {name} ({enum['library']})")
        for member, value in enum["members"]:
            out.append(f"{member}: int = {value}")
        out.append("")
    return "\n".join(out) + "\n"


def emit_generated_init(api):
    """`generated/__init__.py`."""
    numbers = counts(api)
    summary = textwrap.dedent(
        f"""\
        Machine-generated data. Do not edit anything in this package.

        Everything here was read out of the type libraries that ship with the
        installed SOLIDWORKS, by ``python -m swcomapi.tools generate``. It is
        committed to the repository on purpose: the package must install and
        its constants must work on a machine with no SOLIDWORKS on it.

        What was read:

        * {numbers['libraries']} type libraries
        * {numbers['enums']} enumerations, {numbers['constants']} constants
        * {numbers['interfaces']} interfaces, {numbers['members']} members
        * {numbers['documented']} of those members carry a description
        * {numbers['with_out']} have an ``[out]`` parameter
        """
    ).rstrip()
    out = [HEADER.format(summary=summary, source=_source_line(api))]
    out.append("from ._meta import COUNTS, LIBRARIES, SOLIDWORKS_YEAR, UNREADABLE")
    out.append("")
    out.append('__all__ = ["COUNTS", "LIBRARIES", "SOLIDWORKS_YEAR", "UNREADABLE"]')
    return "\n".join(out) + "\n"


def out_shapes(api):
    """Where the ``[out]`` parameters are, keyed by member name.

    Returns ``{(name, kind): [shape, ...]}`` where each shape is::

        {
          "arity": 6,                         # total parameters
          # index, name, VARTYPE, direction
          "outs": [(4, "Errors", 3, "inout"), (5, "Warnings", 3, "inout")],
          "interfaces": ["ISldWorks"],
        }

    Keyed by name rather than by interface because there is no way to ask a
    live SOLIDWORKS object what interface it is: ``IDispatch.GetTypeInfo``
    raises ``TYPE_E_ELEMENTNOTFOUND`` on every one of them.

    Measured, so the shortcut is known to be safe: 982 member names take an
    ``[out]`` parameter, 109 of them appear on more than one interface, and
    only 26 disagree about the shape. Those 26 differ in how many parameters
    they take, so the number of arguments a caller passes tells them apart.
    Anything still ambiguous is reported rather than guessed at.
    """
    shapes = {}
    for interface_name, interface in api["interfaces"].items():
        for member in interface["members"]:
            if not member["has_out"]:
                continue
            outs = [
                (index, param["name"], param["out_vt"], param["direction"])
                for index, param in enumerate(member["params"])
                if param["direction"] in ("out", "inout")
            ]
            key = (member["name"], member["kind"])
            arity = len(member["params"])
            for existing in shapes.setdefault(key, []):
                if existing["arity"] == arity and existing["outs"] == outs:
                    existing["interfaces"].append(interface_name)
                    break
            else:
                shapes[key].append(
                    {"arity": arity, "outs": outs, "interfaces": [interface_name]}
                )

    for entries in shapes.values():
        entries.sort(key=lambda entry: entry["arity"])
        for entry in entries:
            entry["interfaces"].sort()
    return dict(sorted(shapes.items()))


def emit_out_data(api):
    """`generated/_out_data.py`: which parameters a method writes into.

    The one generated table the library needs at run time. Everything else
    generated is either constants or documentation.
    """
    shapes = out_shapes(api)
    ambiguous = sum(1 for entries in shapes.values() if len(entries) > 1)

    out = [
        HEADER.format(
            summary="Which parameters each method writes its results into.",
            source=_source_line(api),
        )
    ]
    out.append(
        f"# {len(shapes)} member names take an [out] or [in,out] parameter.\n"
        f"# {ambiguous} of them have more than one shape across the interfaces\n"
        "# that declare them; those are told apart by how many arguments the\n"
        "# caller passes. `swcomapi.signatures` does the lookup and\n"
        "# `swcomapi.com.call_out` uses it.\n"
        "#\n"
        "# Each entry: (member_name, kind) -> [ (arity, outs, interfaces) ],\n"
        "# where outs is ( (parameter_index, parameter_name, vartype), ... ).\n"
    )
    out.append("OUT_PARAMS = {")
    for (name, kind), entries in shapes.items():
        out.append(f"    ({name!r}, {kind!r}): (")
        for entry in entries:
            outs = ", ".join(
                f"({index}, {pname!r}, {vt}, {direction!r})"
                for index, pname, vt, direction in entry["outs"]
            )
            interfaces = ", ".join(repr(i) for i in entry["interfaces"])
            out.append(f"        ({entry['arity']}, ({outs},), ({interfaces},)),")
        out.append("    ),")
    out.append("}")
    return "\n".join(out) + "\n"


def api_index(api):
    """The whole API as a plain structure, for `swcomapi.apidoc`.

    Shipped as gzipped JSON rather than as a Python module: it is 19,874
    members deep, it is only read when someone asks for help, and JSON keeps
    it out of the import path entirely.
    """
    interfaces = {}
    for name, interface in api["interfaces"].items():
        members = []
        for member in interface["members"]:
            entry = {
                "name": member["name"],
                "kind": member["kind"],
                "doc": member["doc"],
                "returns": member["returns"]["py"],
                "returns_com": member["returns"]["com"],
                "params": [
                    {
                        "name": param["name"],
                        "py": param["py"],
                        "com": param["com"],
                        "dir": param["direction"],
                    }
                    for param in member["params"]
                ],
            }
            if member["com_only"]:
                entry["com_only"] = True
            members.append(entry)
        interfaces[name] = {
            "doc": interface["doc"],
            "library": interface["library"],
            "members": members,
        }

    return {
        "year": api["year"],
        "libraries": [
            {"name": lib["name"], "file": lib["file"]} for lib in api["libraries"]
        ],
        "interfaces": interfaces,
        "enums": {
            name: {
                "library": enum["library"],
                "members": [[member, value] for member, value in enum["members"]],
            }
            for name, enum in api["enums"].items()
        },
    }


def emit_interfaces_stub(api):
    """`interfaces.pyi`: one Protocol per interface.

    For annotating a raw COM object when you want the editor to help::

        from swcomapi.interfaces import IModelDoc2

        def rebuild(doc: IModelDoc2) -> None:
            doc.EditRebuild3()

    Protocols rather than classes because nothing ever subclasses these: a
    COM object is structurally whatever its server says it is.
    """
    out = [
        '"""Stub for swcomapi.interfaces. Generated, do not edit.',
        "",
        "One Protocol per SOLIDWORKS interface, for annotating raw COM objects.",
        "",
        f"Source: {_source_line(api)}",
        '"""',
        "",
        "from typing import Any, Protocol",
        "",
    ]
    for name, interface in api["interfaces"].items():
        out.append(f"class {name}(Protocol):")
        doc = interface["doc"] or f"{name}, from {interface['library']}."
        out.append(f'    """{_escape_doc(doc)}"""')
        emitted = _emit_interface_members(interface)
        out.extend(emitted or ["    ..."])
        out.append("")
    return "\n".join(out) + "\n"


def _emit_interface_members(interface):
    """The body lines of one Protocol."""
    lines = []
    seen = set()
    # A member name can be the same as an interface name - ISketch has both a
    # method called IEnumSketchSegments and a return type of that name - and
    # inside the class body the method wins, which makes the annotation
    # invalid. Any such collision is written as Any.
    shadowed = {member["name"] for member in interface["members"]}
    for member in interface["members"]:
        # The C++-only twins take raw pointers and cannot be called from
        # Python at all, so putting them in the stub would only invite
        # mistakes. `swcomapi.apidoc` still knows about them.
        if member["com_only"]:
            continue
        name = member["name"]
        if name in seen:
            # A property's setter adds nothing to a Protocol beyond its
            # getter, and a duplicate name is a syntax-level redefinition.
            continue
        seen.add(name)

        returns = _annotation(member["returns"]["py"], shadowed)
        if member["kind"] in ("get", "put"):
            lines.append("    @property")
            lines.append(f"    def {name}(self) -> {returns}:")
            lines.append(f'        """{_escape_doc(member["doc"] or name)}"""')
            lines.append("        ...")
            continue

        params = ", ".join(
            f"{_safe_param(param['name'], index)}: {_annotation(param['py'], shadowed)}"
            for index, param in enumerate(member["params"])
        )
        signature = f"self, {params}" if params else "self"
        lines.append(f"    def {name}({signature}) -> {returns}:")
        lines.append(f'        """{_escape_doc(member["doc"] or name)}"""')
        lines.append("        ...")
    return lines


def _annotation(py_type, shadowed=()):
    """A Python annotation for a type name the reader produced.

    py_type
        the type name, as the reader spelled it
    shadowed
        names that a member of the same interface also uses, and which
        therefore cannot be referred to from inside its class body

    Interface names are written bare, not quoted. A stub is never evaluated,
    so a forward reference to an interface declared later in the file resolves
    without help - and quoting it makes ruff rightly complain.
    """
    if py_type in shadowed:
        return "Any"
    if py_type.startswith("I") and py_type[1:2].isupper():
        return py_type
    if py_type in ("None", "int", "float", "str", "bool", "Any"):
        return py_type
    if py_type.startswith("list["):
        return py_type
    # An enumeration or a record referenced by name: it is an int or an
    # opaque value at run time, and Any is the only honest answer.
    return "Any"


def _safe_param(name, index):
    """A parameter name that is a legal Python identifier.

    The libraries use a handful of names that Python reserves - ``from``,
    ``lambda`` - and a few members leave a parameter unnamed.
    """
    import keyword

    if not name or not name.isidentifier() or keyword.iskeyword(name):
        return f"arg{index}"
    return name


def _escape_doc(text):
    """One line of prose, safe to put inside a ``\"\"\"`` docstring."""
    cleaned = " ".join(str(text).split())
    cleaned = cleaned.replace("\\", "\\\\").replace('"""', "'''")
    if cleaned.endswith('"'):
        cleaned += " "
    return cleaned


def emit_interfaces_module(api):
    """`interfaces.py`: the run-time half of the interface Protocols.

    The stub beside it is what matters; this exists so that an annotation
    written without ``from __future__ import annotations`` still imports.
    Each name resolves to an empty ``Protocol`` subclass, built on demand.
    """
    names = sorted(api["interfaces"])
    out = [
        HEADER.format(
            summary=textwrap.dedent(
                f"""\
                Protocols for annotating raw SOLIDWORKS COM objects.

                    from swcomapi.interfaces import IModelDoc2

                    def rebuild(doc: IModelDoc2) -> None:
                        doc.EditRebuild3()

                What the editor and mypy read is ``interfaces.pyi`` beside this
                file, which declares all {len(names)} interfaces with every
                member and its description. This module exists so the same
                import also works at run time, where each name is an empty
                ``Protocol`` subclass: enough to annotate with, and it costs
                nothing until you name one.

                Use ``swcomapi.apidoc`` to look a member up instead of reading
                the stub by hand."""
            ),
            source=_source_line(api),
        )
    ]
    out.append("from typing import Protocol")
    out.append("")
    out.append("INTERFACES = (")
    for name in names:
        out.append(f"    {name!r},")
    out.append(")")
    out.append("")
    out.append("_NAMES = frozenset(INTERFACES)")
    out.append("__all__ = list(INTERFACES)")
    out.append("")
    out.append("")
    out.append("def __getattr__(name):")
    out.append('    """Build an empty Protocol for an interface name (PEP 562)."""')
    out.append("    if name not in _NAMES:")
    out.append("        raise AttributeError(")
    out.append("            f\"module {__name__!r} has no interface {name!r}. \"")
    out.append('            f"Try swcomapi.apidoc.find({name!r}) to search."')
    out.append("        )")
    out.append("    built = type(name, (Protocol,), {\"__module__\": __name__})")
    out.append("    globals()[name] = built")
    out.append("    return built")
    out.append("")
    out.append("")
    out.append("def __dir__():")
    out.append("    return list(INTERFACES)")
    return "\n".join(out) + "\n"


def _enum_summary(name, enum):
    """A one-line description for an enumeration that has none.

    Not one of the 14,889 constants carries a description in the type
    libraries, and nor do most enumerations, so the stub says something
    factual rather than nothing.
    """
    return f"{name} ({len(enum['members'])} constants, from {enum['library']})."


def _source_line(api):
    """The provenance line for a generated file's docstring.

    Names the release and the libraries, never a path or a timestamp: the
    output has to be byte-identical when regenerated from the same install.
    """
    year = api["year"] or "unknown"
    files = ", ".join(lib["file"] for lib in api["libraries"])
    line = f"SOLIDWORKS {year} type libraries ({files})"
    # Ten library names overflow any sensible line length, so it is wrapped
    # here rather than left for the linter to complain about.
    return "\n".join(textwrap.wrap(line, width=78, subsequent_indent="  "))


# -------------------------------------------------------------------- writing


def package_root():
    """The ``src/swcomapi`` directory this module lives in."""
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def write(api, root=None):
    """Write every generated file. Returns a list of (path, bytes_written).

    Files are written with explicit UTF-8 and Unix newlines, so that the
    output does not depend on the machine's locale or on git's autocrlf.
    """
    root = root or package_root()
    generated = os.path.join(root, GENERATED_DIR)
    os.makedirs(generated, exist_ok=True)

    files = {
        os.path.join(generated, "__init__.py"): emit_generated_init(api),
        os.path.join(generated, "_meta.py"): emit_meta(api),
        os.path.join(generated, "_enum_data.py"): emit_enum_data(api),
        os.path.join(generated, "_out_data.py"): emit_out_data(api),
        os.path.join(root, "enums.pyi"): emit_enums_stub(api),
        os.path.join(root, "const.pyi"): emit_const_stub(api),
        os.path.join(root, "interfaces.py"): emit_interfaces_module(api),
        os.path.join(root, "interfaces.pyi"): emit_interfaces_stub(api),
    }

    written = []
    for path, text in sorted(files.items()):
        with open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
        written.append((path, len(text.encode("utf-8"))))

    written.append(write_index(api, generated))
    return written


def write_index(api, generated):
    """Write ``generated/api_index.json.gz``. Returns ``(path, bytes)``.

    Gzipped JSON, with ``mtime=0`` so the bytes do not change between runs -
    gzip normally stamps the time into its header, which would break the
    reproducibility check. Sorted keys and no indentation, for the same
    reason and for size.
    """
    import gzip
    import json

    path = os.path.join(generated, "api_index.json.gz")
    payload = json.dumps(
        api_index(api), sort_keys=True, separators=(",", ":"), ensure_ascii=False
    ).encode("utf-8")
    with open(path, "wb") as handle:
        with gzip.GzipFile(fileobj=handle, mode="wb", mtime=0) as archive:
            archive.write(payload)
    return path, os.path.getsize(path)


def run(paths=None, root=None):
    """Gather, check and write. Returns ``(api, written)``."""
    api = gather(paths)
    check(api)
    return api, write(api, root)
